// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2LDKTB7QUoTdDCO7QU1qnSpm_LpQbSE',
    appId: '1:966064832463:web:81dbc73cee0085a095dcba',
    messagingSenderId: '966064832463',
    projectId: 'expense-7a649',
    authDomain: 'expense-7a649.firebaseapp.com',
    storageBucket: 'expense-7a649.appspot.com',
    measurementId: 'G-C8FP3B3Q0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCycp3hkkocIdk1i3iz4t3PR91XMu0LAJU',
    appId: '1:966064832463:android:2c98b9ea4b06e82895dcba',
    messagingSenderId: '966064832463',
    projectId: 'expense-7a649',
    storageBucket: 'expense-7a649.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8kSgnEZYWXaMPeQAEEaw7EeWihgcY758',
    appId: '1:966064832463:ios:a01bfff1ef0dcac795dcba',
    messagingSenderId: '966064832463',
    projectId: 'expense-7a649',
    storageBucket: 'expense-7a649.appspot.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8kSgnEZYWXaMPeQAEEaw7EeWihgcY758',
    appId: '1:966064832463:ios:cf62f4972bf74b9595dcba',
    messagingSenderId: '966064832463',
    projectId: 'expense-7a649',
    storageBucket: 'expense-7a649.appspot.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
